name: raphael
favicon: null
layout_spectrum: 0.9350494965910912
typography_spectrum: 0.8945226424839348
title: raphael's place
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d8c7b3'
    - '#090b0a'
    - '#4f7ed8'
    - '#fef5d6'
    - '#585439'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
